using System;
using RedlineLegends.Utilities;
using UnityEngine;

namespace RedlineLegends.Tracks
{
    /// <summary>
    /// Dense polyline down the middle (or ideal line) of the track with a target speed per node.
    /// Used for race progress/ranking, wrong-way detection and AI driving. Generated by the track
    /// tooling; nothing at runtime edits it.
    /// </summary>
    [Serializable]
    public sealed class RacingLine
    {
        [SerializeField] private Vector3[] points = Array.Empty<Vector3>();
        [SerializeField] private float[] targetSpeeds = Array.Empty<float>();
        [SerializeField] private float[] halfWidths = Array.Empty<float>();
        [SerializeField] private float[] cumulative = Array.Empty<float>();
        [SerializeField] private float totalLength;
        [SerializeField] private bool loop = true;

        public int Count => points.Length;
        public float TotalLength => totalLength;
        public bool Loop => loop;
        public Vector3[] Points => points;
        public float[] TargetSpeeds => targetSpeeds;

        public Vector3 Point(int i) => points[Wrap(i)];
        public float TargetSpeed(int i) => targetSpeeds[Wrap(i)];
        public float HalfWidth(int i) => halfWidths.Length > 0 ? halfWidths[Wrap(i)] : 6f;
        public float DistanceAtNode(int i) => cumulative[Wrap(i)];

        public int Wrap(int i)
        {
            int n = points.Length;
            if (n == 0) return 0;
            if (loop)
            {
                i %= n;
                if (i < 0) i += n;
                return i;
            }
            return Mathf.Clamp(i, 0, n - 1);
        }

        /// <summary>Unit direction of the segment leaving node i (flat).</summary>
        public Vector3 DirectionAt(int i)
        {
            Vector3 a = Point(i);
            Vector3 b = Point(i + 1);
            if (!loop && i >= points.Length - 1) { a = Point(i - 1); b = Point(i); }
            Vector3 d = b - a;
            d.y = 0f;
            return d.sqrMagnitude > 1e-6f ? d.normalized : Vector3.forward;
        }

        public Vector3 RightAt(int i) => Vector3.Cross(Vector3.up, DirectionAt(i));

        /// <summary>
        /// Nearest node searched locally around a hint (racers move continuously, so a window of a
        /// few nodes per query is enough and keeps ranking O(racers)). A negative hint searches all.
        /// </summary>
        public int FindNearest(Vector3 position, int hint, int window = 12)
        {
            int n = points.Length;
            if (n == 0) return 0;
            int best = 0;
            float bestDist = float.MaxValue;
            if (hint < 0 || window >= n / 2)
            {
                for (int i = 0; i < n; i++)
                {
                    float d = FlatSqrDistance(points[i], position);
                    if (d < bestDist) { bestDist = d; best = i; }
                }
                return best;
            }
            for (int k = -window; k <= window; k++)
            {
                int i = Wrap(hint + k);
                float d = FlatSqrDistance(points[i], position);
                if (d < bestDist) { bestDist = d; best = i; }
            }
            return best;
        }

        /// <summary>Distance along the line (0..TotalLength) of the projection of a position near node index.</summary>
        public float DistanceAlong(Vector3 position, int nearestIndex)
        {
            int n = points.Length;
            if (n < 2) return 0f;
            // Project onto the segment before and after the nearest node; take the closer one.
            Vector3 p = position;
            Vector3 a0 = Point(nearestIndex - 1), a1 = Point(nearestIndex), a2 = Point(nearestIndex + 1);
            float tPrev = MathUtil.ProjectOnSegment(p, a0, a1, out var cPrev);
            float tNext = MathUtil.ProjectOnSegment(p, a1, a2, out var cNext);
            bool usePrev = FlatSqrDistance(cPrev, p) < FlatSqrDistance(cNext, p);
            float dist;
            if (usePrev)
            {
                int prev = Wrap(nearestIndex - 1);
                float segLen = Vector3.Distance(a0, a1);
                dist = cumulative[prev] + tPrev * segLen;
            }
            else
            {
                float segLen = Vector3.Distance(a1, a2);
                dist = cumulative[nearestIndex] + tNext * segLen;
            }
            if (loop && dist >= totalLength) dist -= totalLength;
            return Mathf.Clamp(dist, 0f, totalLength);
        }

        public Vector3 PointAtDistance(float distance)
        {
            int n = points.Length;
            if (n == 0) return Vector3.zero;
            if (loop) distance = Mathf.Repeat(distance, totalLength);
            else distance = Mathf.Clamp(distance, 0f, totalLength);
            int i = IndexAtDistance(distance);
            float segStart = cumulative[i];
            float segLen = Vector3.Distance(Point(i), Point(i + 1));
            float t = segLen > 1e-4f ? Mathf.Clamp01((distance - segStart) / segLen) : 0f;
            return Vector3.Lerp(Point(i), Point(i + 1), t);
        }

        /// <summary>Index of the node at or before the given distance (binary search).</summary>
        public int IndexAtDistance(float distance)
        {
            int lo = 0, hi = cumulative.Length - 1;
            while (lo < hi)
            {
                int mid = (lo + hi + 1) >> 1;
                if (cumulative[mid] <= distance) lo = mid; else hi = mid - 1;
            }
            return lo;
        }

        private static float FlatSqrDistance(Vector3 a, Vector3 b)
        {
            float dx = a.x - b.x, dz = a.z - b.z;
            return dx * dx + dz * dz;
        }

        /// <summary>Builds the line from ordered points; target speeds come from curvature and grip.</summary>
        public static RacingLine Build(Vector3[] pts, float[] halfWidth, bool isLoop, float lateralG, float maxSpeedMs)
        {
            var line = new RacingLine { points = pts, loop = isLoop };
            int n = pts.Length;
            line.halfWidths = halfWidth != null && halfWidth.Length == n ? halfWidth : new float[0];
            line.cumulative = new float[n];
            float total = 0f;
            for (int i = 0; i < n; i++)
            {
                line.cumulative[i] = total;
                int next = isLoop ? (i + 1) % n : Mathf.Min(i + 1, n - 1);
                total += Vector3.Distance(pts[i], pts[next]);
            }
            line.totalLength = total;

            // Speed from the radius of the circle through three consecutive nodes, then a backward
            // pass so braking zones are physically reachable (v_prev <= sqrt(v^2 + 2 a d)).
            var speeds = new float[n];
            for (int i = 0; i < n; i++)
            {
                Vector3 a = pts[line.Wrap(i - 2)], b = pts[i], c = pts[line.Wrap(i + 2)];
                float radius = CircleRadius(a, b, c);
                float v = Mathf.Sqrt(Mathf.Max(0.1f, lateralG * 9.81f * radius));
                speeds[i] = Mathf.Min(maxSpeedMs, v);
            }
            float brakeDecel = lateralG * 9.81f * 0.8f;
            int passes = isLoop ? 2 : 1;
            for (int p = 0; p < passes; p++)
            {
                for (int k = n - 1; k >= 0; k--)
                {
                    int i = k;
                    int next = line.Wrap(i + 1);
                    float d = Vector3.Distance(pts[i], pts[next]);
                    float allowed = Mathf.Sqrt(speeds[next] * speeds[next] + 2f * brakeDecel * d);
                    if (speeds[i] > allowed) speeds[i] = allowed;
                }
            }
            line.targetSpeeds = speeds;
            return line;
        }

        private static float CircleRadius(Vector3 a, Vector3 b, Vector3 c)
        {
            a.y = b.y = c.y = 0f;
            float ab = Vector3.Distance(a, b), bc = Vector3.Distance(b, c), ca = Vector3.Distance(c, a);
            float s = (ab + bc + ca) * 0.5f;
            float area = Mathf.Sqrt(Mathf.Max(0f, s * (s - ab) * (s - bc) * (s - ca)));
            if (area < 1e-3f) return 10000f; // straight
            return ab * bc * ca / (4f * area);
        }
    }
}
